name: CI

on:
  push:
    branches:
      - master

jobs:
    build-and-tests:
      runs-on: ubuntu-latest
      steps:
       - name: Checkout repository # Faz o GitHub Actions baixar o código do repositório no runner.
         uses: actions/checkout@v3

       - name: Setup .NET # Instala o .NET 7 no runner.
         uses: actions/setup-dotnet@v3
         with:
           dotnet-version: '7.0.x'

       - name: Restore dependencies # Restaura os pacotes NuGet do seu projeto.
         run: dotnet restore ClientManagerBackend/ClientManagerBackend.sln

       - name: Build # Compila o projeto. --no-restore evita restaurar pacotes novamente, já que fizemos antes.
         run: dotnet build ClientManagerBackend/ClientManagerBackend.sln --configuration Release --no-restore

       - name: Run tests with coverage #Executa os testes unitários. --no-build evita recompilar, usando o build anterior. 
         run: dotnet test ClientManagerBackend/ClientManagerBackend.sln --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

       - name: Publish code coverage results # Publica os resultados de cobertura de código.
         uses: codecov/codecov-action@v3
         with:
           files: ClientManagerBackend/ClientManagerBackend.Tests/TestResults/coverage.cobertura.xml